name = "r2-registry"

# Custom Cloudflare domain for worker: 
# routes = [
#  { pattern = "your.custom.domain", custom_domain = true } 
# ]

main = "./index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

r2_buckets = [
  { binding = "REGISTRY", bucket_name = "" }
]
